# Generated by Django 4.0.6 on 2022-07-07 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_poll_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='option_four',
            new_name='option_1',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='option_one',
            new_name='option_2',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='option_three',
            new_name='option_3',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='option_two',
            new_name='option_4',
        ),
    ]
