# Generated by Django 4.0.6 on 2022-07-07 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_option_1_poll_option1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='base.poll'),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
