# Generated by Django 4.0.6 on 2022-07-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_response_poll_alter_response_response_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='poll',
        ),
    ]
