# Generated by Django 3.2.7 on 2022-07-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220707_0042'),
        ('base', '0010_responsemodel_delete_response'),
    ]

    operations = [
    ]
